var hnmeta = {
    lessons: {


        1: { yt: ['https://www.youtube.com/watch?v=FfhrWYOnlJ8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=1', 'https://www.youtube.com/watch?v=1kHPmlw0umY&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=2', 'https://www.youtube.com/watch?v=nq0RsUi8k_0&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=3'], 
            slides: 'Hidayatun Nahw 1',
            page: 6,
            deck: '',},
        2: { yt: 'https://www.youtube.com/watch?v=TiRCbMsLVZI&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=4', 
            slides: 'Hidayatun Nahw 2',
            page: 6,
            deck: '',},
        3: { yt: 'https://www.youtube.com/watch?v=Wt61BfYHj20&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=5', 
            slides: 'Hidayatun Nahw 3',
            page: 7,
            deck: '',},
        4: { yt: ['https://www.youtube.com/watch?v=L_4UW5kJpD8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=6', 'https://www.youtube.com/watch?v=4PStsBsO6II&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=7',],
            slides: 'Hidayatun Nahw 4',
            page: 7,
            deck: '',},
        5: { yt: ['https://www.youtube.com/watch?v=ZtTBJRL0Whw&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=8', 'https://www.youtube.com/watch?v=x1Tz5k-8vF0&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=9', 'https://www.youtube.com/watch?v=kHCas-zyvmQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=10',], 
            slides: 'Hidayatun Nahw 5',
            page: 8,
            deck: '',},
        6: { yt: ['https://www.youtube.com/watch?v=_KpYXXnLhMk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=11', 'https://www.youtube.com/watch?v=rg3l9pv7Kk8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=12',], 
            slides: 'Hidayatun Nahw 6',
            page: 9,
            deck: '',},
        7: { yt: ['https://www.youtube.com/watch?v=_WF_H5aUdnU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=13', 'https://www.youtube.com/watch?v=ffxyEs6V8_8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=14',], 
            slides: 'Hidayatun Nahw 7 المقدمة، الفصل الثاني، الحرف',
            page: 9,
            deck: '',},
        8: { yt: ['https://www.youtube.com/watch?v=QGFOVdtUFE8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=15', 'https://www.youtube.com/watch?v=HvWuLohYpSE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=16',], 
            slides: 'Hidayatun Nahw 8 المقدمة، الفصل الثالث في تعريف الكلام',
            page: 11,
            deck: '',},
        9: { yt: 'https://www.youtube.com/watch?v=odHlNoFNklk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=17', 
            slides: 'Hidayatun Nahw 9 القسم الأول',
            page: 11,
            deck: '',},

        10: { yt: ['https://www.youtube.com/watch?v=9QlwG7f8bZ8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=18', 'https://www.youtube.com/watch?v=5-H7LEYvwF4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=19'], 
            slides: 'Hidayatun Nahw 10 القسم الأول، الباب الأول، المقدمة، الفصل الأول',
            page: 12,
            deck: '',},
        11: { yt: 'https://www.youtube.com/watch?v=0hZbf0oOZpA&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=20', 
            slides: 'Hidayatun Nahw 11 القسم الأول، الباب الأول، المقدمة الفصل الثاني',
            page: 12,
            deck: '',},
        12: { yt: ['https://www.youtube.com/watch?v=eG04Qp5_sDQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=21', 'https://www.youtube.com/watch?v=kmwmsoMhAPU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=22', 'https://www.youtube.com/watch?v=j92nKcpUCJY&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=23', 'https://www.youtube.com/watch?v=H1JiqBGXV2o&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=24', 'https://www.youtube.com/watch?v=6AYjiZEPhgk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=25', 'https://www.youtube.com/watch?v=SpAvgHtgb_M&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=26', 'https://www.youtube.com/watch?v=NHNY82z9GYs&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=27', 'https://www.youtube.com/watch?v=MEK5XIlMJKE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=28', 'https://www.youtube.com/watch?v=z_JTmp1hOPo&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=29',], 
            slides: 'Hidayatun Nahw 12 القسم الأول، الباب الأول، المقدمة، الفصل الثالث',
            page: 13,
            deck: '',},
        13: { yt: ['https://www.youtube.com/watch?v=5QJwveQ18lw&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=30', 'https://www.youtube.com/watch?v=cNLgpqhsRrE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=31', 'https://www.youtube.com/watch?v=EUiGPJ3MDL4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=32', 'https://www.youtube.com/watch?v=IN3lWUmxe-0&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=33', 'https://www.youtube.com/watch?v=hP6z7hRCXbU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=34', 'https://www.youtube.com/watch?v=qHZuW5RyytI&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=35', 'https://www.youtube.com/watch?v=3PqryQ-m-hk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=36', 'https://www.youtube.com/watch?v=2Sx7Lk6jqnU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=37', 'https://www.youtube.com/watch?v=VO_6nQgZ0U4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=38', 'https://www.youtube.com/watch?v=catrHU-oHMc&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=39', 'https://www.youtube.com/watch?v=UvvV1SvPHeo&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=40', 'https://www.youtube.com/watch?v=cEeYPXNs96I&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=41', 'https://www.youtube.com/watch?v=PQXhWDg0e50&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=42', 'https://www.youtube.com/watch?v=NWyuMx2yNgo&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=43',], 
            slides: 'Hidayatun Nahw 13 القسم الأول، الباب الأول، الفصل الرابع',
            page: 17,
            deck: '',},
        14: { yt: ['https://www.youtube.com/watch?v=xXJfOKtrtxk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=44', 'https://www.youtube.com/watch?v=nj-nYXvI4cg&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=45', 'https://www.youtube.com/watch?v=rx4M-mD_I_o&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=46', 'https://www.youtube.com/watch?v=2ZA2GjiiIlg&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=47', 'https://www.youtube.com/watch?v=iTzMkiCFLQk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=48', 'https://www.youtube.com/watch?v=cRx4SjcYXvw&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=49',], 
            slides: 'Hidayatun Nahw 14 القسم الأول، الباب الأول، المقصد الأول، الفصل الأول، الفاعل',
            page: 22,
            deck: '',},
        15: { yt: ['https://www.youtube.com/watch?v=IIa6gH72_YU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=50', 'https://www.youtube.com/watch?v=_cnGFDzkNBI&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=51', 'https://www.youtube.com/watch?v=7RK9zlVhOIQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=52', 'https://www.youtube.com/watch?v=M2OkpxJGeIw&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=53', 'https://www.youtube.com/watch?v=NL7UiQWt6kE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=54',], 
            slides: 'Hidayatun Nahw 15 القسم الأول، الباب الأول، المقصد الأول، الفصل الثاني، تنازع الفعلين',
            page: 25,
            deck: '',},
        16: { yt: ['https://www.youtube.com/watch?v=19nvnyk4WV0&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=55', 'https://www.youtube.com/watch?v=TPBbzwu7JPI&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=56',], 
            slides: 'Hidayatun Nahw 16 القسم الأول، الباب الأول، المقصد الأول، الفصل الثالث، مفعول ما لم يسم فاعله',
            page: 30,
            deck: '',},
        17: { yt: ['https://www.youtube.com/watch?v=o6cMWhSkDag&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=57', 'https://www.youtube.com/watch?v=IuSYlqdGDsc&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=58', 'https://www.youtube.com/watch?v=oInXWANsWLg&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=59', 'https://www.youtube.com/watch?v=oWZWXV8qfUE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=60',], 
            slides: 'Hidayatun Nahw 17 القسم الأول، الباب الأول، المقصد الأول، الفصل الرابع، المبتدأ والخبر',
            page: 30,
            deck: '',},
        18: { yt: 'https://www.youtube.com/watch?v=4BT4o7N3H-Q&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=61', 
            slides: 'Hidayatun Nahw 18 القسم الأول، الباب الأول، المقصد الأول، الفصل الخامس، خبر إن وأخواتها',
            page: 33,
            deck: '',},
        19: { yt: 'https://www.youtube.com/watch?v=O0f9rYE4WOA&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=62', 
            slides: 'Hidayatun Nahw 19 القسم الأول، الباب الأول، المقصد الأول، الفصل السَادس، اسم كان وأخواتها',
            page: 33,
            deck: '',},

        20: { yt: 'https://www.youtube.com/watch?v=UD1QcXDMhpM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=63', 
            slides: 'Hidayatun Nahw 20 القسم الأول، الباب الأول، المقصد الأول، الفصل السابع، ما ولا المشبهتان بليس',
            page: 34,
            deck: '',},
        21: { yt: 'https://www.youtube.com/watch?v=IHj8N16G-1E&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=64', 
            slides: 'Hidayatun Nahw 21 القسم الأول، الباب الأول، المقصد الأول، الفصل الثامن، خبر لا لنفي الجنس',
            page: 35,
            deck: '',},
        22: { yt: 'https://www.youtube.com/watch?v=guUhCGthAtY&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=65', 
            slides: 'Hidayatun Nahw 22 القسم الأول، الباب الأول، المقصد الثاني، الفصل الأول، مفعول مطلق',
            page: 35,
            deck: '',},
        23: { yt: ['https://www.youtube.com/watch?v=Eo0649-FXeQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=66', 'https://www.youtube.com/watch?v=5daiBY2UQv4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=67', 'https://www.youtube.com/watch?v=Th4zj4PNflo&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=68', 'https://www.youtube.com/watch?v=hPjsVhYwFro&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=69', 'https://www.youtube.com/watch?v=FXwJgBhSVWc&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=70', 'https://www.youtube.com/watch?v=uG6HwMRSsxQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=71'], 
            slides: 'Hidayatun Nahw 23 القسم الأول، الباب الأول، المقصد الثاني، الفصل الثاني، مفعول به',
            page: 36,
            deck: '',},
        24: { yt: 'https://www.youtube.com/watch?v=Z5Z9yAAd1uQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=72', 
            slides: 'Hidayatun Nahw 24 القسم الأول، الباب الأول، المقصد الثاني، الفصل الثالث، المفعول فيه',
            page: 39,
            deck: '',},
        25: { yt: 'https://www.youtube.com/watch?v=xb00g1qbV3Q&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=73', 
            slides: 'Hidayatun Nahw 25 القسم الأول، الباب الأول، المقصد الثاني، الفصل الرابع، المفعول له',
            page: 40,
            deck: '',},
        26: { yt: ['https://www.youtube.com/watch?v=4LS30x-3oAQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=74', 'https://www.youtube.com/watch?v=7FFr_MH7Y3U&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=75', 'https://www.youtube.com/watch?v=SW2N5x24Rdw&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=76'], 
            slides: 'Hidayatun Nahw 26 القسم الأول، الباب الأول، المقصد الثاني، الفصل الخامس، المفعول معه',
            page: 41,
            deck: '',},
        27: { yt: ['https://www.youtube.com/watch?v=1NWnCnlphHI&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=77', 'https://www.youtube.com/watch?v=WyaGNsos5PQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=78', 'https://www.youtube.com/watch?v=X8FZ14Za33Q&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=79',], 
            slides: 'Hidayatun Nahw 27 القسم الأول، الباب الأول، المقصد الثاني، الفصل السادس، الحال',
            page: 41,
            deck: '28cff75ecfa64aa3a01dd44c7a4a9532',},
        28: { yt: ['https://www.youtube.com/watch?v=-y22SSeiuFM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=80', 'https://www.youtube.com/watch?v=fs0LaXkpcTY&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=81',], 
            slides: 'Hidayatun Nahw 28 القسم الأول، الباب الأول، المقصد الثاني، الفصل السابع، التمييز',
            page: 43,
            deck: 'fac6a970ce9b4e4ba3f8af5db732f369',},
        29: { yt: ['https://www.youtube.com/watch?v=yN9XEPlpxFs&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=82', 'https://www.youtube.com/watch?v=FSv_FiqirBM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=83', 'https://www.youtube.com/watch?v=MUBfDX49FxQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=84', 'https://www.youtube.com/watch?v=vtIjPPAsI7k&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=85', 'https://www.youtube.com/watch?v=a2HQYmQ2_os&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=86', 'https://www.youtube.com/watch?v=tV6ZUat9KQM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=87',], 
            slides: 'Hidayatun Nahw 29 القسم الأول، الباب الأول، المقصد الثاني، الفصل الثامن، المستثنی',
            page: 43,
            deck: 'b914b6c6fea742e0acba67a87f806d9f',},

        30: {
            yt: 'https://www.youtube.com/watch?v=Vhl4n7gut94&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=88',
            slides: 'Hidayatun Nahw 30 القسم الأول، الباب الأول، المقصد الثاني، الفصل التاسع، خبر كان',
            page: 46,
            deck: 'df2c703a086249ce86ce25e0e3d07821',
        },
        31: {
            yt: 'https://www.youtube.com/watch?v=gmOn5D2-Ko4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=89',
            slides: 'Hidayatun Nahw 31 القسم الأول، الباب الأول، المقصد الثاني، الفصل العاشر، اسم إن وأخواتها',
            page: 46,
            deck: '23e14679edc648c7ad965b73922db8d8',
        },
        32: { yt: 'https://www.youtube.com/watch?v=vb8VJFSojrE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=90', 
            slides: 'Hidayatun Nahw 32 القسم الأول، الباب الأول، المقصد الثاني، الفصل الحادي عشر، المنصوب بلا التي لنفي الجنس',
            page: 46,
            deck: '931aab2378f74f13b6edb1ffec8602d9',
        },
        33: { yt: 'https://www.youtube.com/watch?v=AxbvJEmrYAY&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=91', 
            slides: 'Hidayatun Nahw 33 القسم الأول، الباب الأول، المقصد الثاني، الفصل الحادي عشر، خبر ما ولا المشبهتين بليس',
            page: 47,
            deck: '5623d1fc1e92498fb0a9b252043bef03',
        },
        34: {
            title: '34. Majroor - Hidayatun Nahw Lesson 34 المجرور',
            slides: 'Hidayatun Nahw 34 القسم الأول، الباب الأول، المقصد الثالث',
            yt: ['https://www.youtube.com/watch?v=lHUKw718K7A&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=92',
                'https://www.youtube.com/watch?v=ZYa8NB2pv_Y&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=93',
                'https://www.youtube.com/watch?v=_94BF4isDQc&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=94'
            ],
            page: 48,
            deck: '35854bf5670b4f6cb37677afed800c0a',
        },

        35: {
            title: 'Tawabi3. Hidayatun Nahw Lesson 35 التوابع',
            slides: 'Hidayatun Nahw 35 القسم الأول، الباب الأول، الخاتمة في التوابع',
            yt: 'https://www.youtube.com/watch?v=221S7RbaiVM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=95',
            page: 51,
            deck: 'fc594cf6e6fb48c0a1209e724699add8',
        },
        36: {
            title: '36. na3t. Hidayatun Nahw Lesson 36 النعت',
            slides: 'Hidayatun Nahw 36 القسم الأول، الباب الأول، الخاتمة في التوابع، النعت',
            yt: ['https://www.youtube.com/watch?v=pzNIRr4COIU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=96',
                'https://www.youtube.com/watch?v=Ko9KIjgl-94&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=97',
            ],
            page: 51,
            deck: '0458a59d40a846a99275c419137bdce3',
        },
        37: {
            title: '37. 3aTf. Hidayatun Nahw Lesson 37 العطف بالحرف، عطف النسق',
            slides: 'Hidayatun Nahw 37 القسم الأول، الباب الأول، الخاتمة في التوابع، العطف بالنسق',
            yt: 'https://www.youtube.com/watch?v=N3jrg7tlr4Q&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=98',
            page: 52,
            deck: '468d5f2186a94299a2c448426511ba50',
        },
        38: {
            title: '38. ta\'keed. Hidayatun Nahw Lesson 38 التأكيد',
            slides: 'Hidayatun Nahw 38 القسم الأول، الباب الأول، الخاتمة في التوابع، التأكيد',
            yt: 'https://www.youtube.com/watch?v=X0TC5Xnrwqk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=99',
            page: 54,
            deck: '437220868959498a90b8b141f3aac138',
        },
        39: {
            title: '39. Badl. Hidayatun Nahw Lesson 39 البدل',
            slides: 'Hidayatun Nahw 39 القسم الأول، الباب الأول، الخاتمة في التوابع، البدل',
            yt: 'https://www.youtube.com/watch?v=JEhRe9dMBso&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=100',
            page: 56,
            deck: 'eab6576aa74940959373975ff5cae848',
        },
        40: {
            title: '40. 3aTf bayaan; Hidayatun Nahw Lesson 40 عطف البيان',
            slides: 'Hidayatun Nahw 40 القسم الأول، الباب الأول، الخاتمة في التوابع، عطف البيان',
            yt: 'https://www.youtube.com/watch?v=xmX76BUoE7c&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=101',
            page: 57,
            deck: '59e0cd4d03914d53b6519fe2fa0fcc6a',
        },



        41: {
            title: 'asmaaul mabniyy - Baab II - 8 sections. Hidayatun Nahw Lesson 41 الاسم المبني',
            yt: 'https://www.youtube.com/watch?v=8zslzVDUt2M&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=102',
            slides: 'Hidayatun Nahw 41 القسم الأول، الباب الثاني، الاسم المبني',
            page: 57,
            deck: '11535b9da9044ec2be7b92bc3e9a184d',
        },
        42: {
            title: 'asmaaul mudmaraat. Hidayatun Nahw Lesson 42 المضمرات',
            yt: 'https://www.youtube.com/watch?v=0f0dXtdrTpI&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=103',
            slides: 'Hidayatun Nahw 42 القسم الأول، الباب الثاني، الاسم المبني، الفصل الأول، المضمرات',
            page: 58,
            deck: '7ad076eb59c14613833693b10a97ef12',
        },
        43: {
            title: ' asmaaul isharah. Hidayatun Nahw Lesson 43 أسماء الإشارة',
            yt: 'https://www.youtube.com/watch?v=GfwMV32gqZE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=104',
            slides: 'Hidayatun Nahw 43 القسم الأول، الباب الثاني، الاسم المبني، الفصل الثاني، أسماء الإشارة',
            page: 60,
            deck: '9e732fc920624a56888e1fa193655db8',
        },
        44: {
            title: 'asmaaul mawsool. Hidayatun Nahw Lesson 44 الاسم الموصول',
            yt: 'https://www.youtube.com/watch?v=Ycr_TH63tlM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=105',
            slides: 'Hidayatun Nahw 44 القسم الأول، الباب الثاني، الاسم المبني، الفصل الثالث، الأسماء الموصولة',
            page: 61,
            deck: '59241c0b6d49462488e8e982cbc339e7',
        },
        45: {
            title: 'asmaaul af3aal Lesson 45',
            yt: 'https://www.youtube.com/watch?v=H8Ai-Radars&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=107&t=0s',
            slides: 'Hidayatun Nahw 45 القسم الأول، الباب الثاني، الاسم المبني، الفصل الرابع، أسماء الأفعال',
            page: 62,
            deck: 'ad348ad47f3b417a9cba4a6d1fa8a2c7',
        },
        46: {
            title: 'asmaaul aSwaat Lesson 46',
            yt: 'https://www.youtube.com/watch?v=px_mmxVx2W0&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=107',
            slides: 'Hidayatun Nahw 46 القسم الأول، الباب الثاني، الاسم المبني، الفصل الخامس، الأصوات',
            page: 63,
            deck: '6e6622ab8d5241928365f88dd58cb8c8',
        },
        47: {
            title: 'asmaaul Murakkabaat - 6 sub-sections',
            yt: 'https://www.youtube.com/watch?v=yJ0SJvlJhJk&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=108',
            slides: 'Hidayatun Nahw 47 القسم الأول، الباب الثاني، الاسم المبني، الفصل السادس المركبات',
            page: 63,
            deck: 'e5975f73307649aaabd290107a03c072',
        },
        48: {
            title: 'asmaaul Kinaayaat. Hidayatun Nahw Lesson 48 الكنايات',
            yt: 'https://www.youtube.com/watch?v=afsVoci-Ej8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=109',
            slides: 'Hidayatun Nahw 48 القسم الأول، الباب الثاني، الاسم المبني، الفصل السابع، الكنايات',
            page: 64,
            deck: 'f96c38271ea34d9bb503e8e761d963bc',
        },
        49: {
            title: 'Zuruwf mabniyyah - Hidayatun Nahw Lesson 49 الظروف المبنية',
            yt: 'https://www.youtube.com/watch?v=khaID8-1iPQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=110',
            slides: 'Hidayatun Nahw 49 القسم الأول، الباب الثاني، الاسم المبني، الفصل السابع، الظروف المبنية',
            page: 65,
            deck: '399fef9ca8374065b862fd64c44e75f8',
        },




        50: {
            title: '50. Khatima - 10 sections',
            slides: 'Hidayatun Nahw 50 القسم الأول، الخاتمة، الفصل الأول التعريف والتنكير',
            yt: 'https://www.youtube.com/watch?v=eA2vO2_NNDo&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=111',
            page: 69,
            deck: '55262030cd69494097a2e597e0728d55',
        },
        51: {
            title: '51. Hidayatun Nahw Lesson 51 أسماء العدد (Numbers)            ',
            slides: 'Hidayatun Nahw 51 القسم الأول، الخاتمة، الفصل الثاني أسماء العدد',
            yt: 'https://www.youtube.com/watch?v=_RD2Hs_KXsU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=112',
            page: 70,
            deck: 'e3e14dbba03648dd883a3f78479dd363',
        },
        52: {
            title: '52. Hidayatun Nahw Lesson 52 المذكر والمؤنث            ',
            slides: 'Hidayatun Nahw 52 القسم الأول، الخاتمة، الفصل الثالث، التذكير والتأنيث',
            yt: 'https://www.youtube.com/watch?v=r6YGXXHOsh4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=113',
            page: 73,
            deck: '8e1fc966847d416e88a906fc8ce064e8',
        },
        53: {
            title: '53. Hidayatun Nahw Lesson 53 المثنى            ',
            slides: 'Hidayatun Nahw 53 القسم الأول، الخاتمة، الفصل الرابع، المثنی',
            yt: 'https://www.youtube.com/watch?v=50gIy5nf-ZQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=114',
            page: 73,
            deck: 'f1e9cc7ae1e54b8e804c4177ed742147',
        },
        54: {
            title: '54. Hidayatun Nahw Lesson 54 المجموع            ',
            slides: 'Hidayatun Nahw 54 القسم الأول، الخاتمة، الفصل الخامس، المجموع',
            yt: 'https://www.youtube.com/watch?v=YZsgxfXbuuE&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=115',
            page: 75,
            deck: '9c48cbbae03445ba9f04672b4c25be0b',
        },
        55: {
            title: '55. Hidayatun Nahw Lesson 55 المصدر            ',
            slides: 'Hidayatun Nahw 55 القسم الأول، الخاتمة، الفصل السادس، المصدر',
            yt: 'https://www.youtube.com/watch?v=qxE0PSfwAV4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=116',
            page: 78,
            deck: '3a4a5e471f4048948c99ae8f884b3d6f',
        },
        56: {
            title: '56. Hidayatun Nahw Lesson 56 اسم الفاعل            ',
            slides: 'Hidayatun Nahw 56 القسم الأول، الخاتمة، الفصل السابع، اسم الفاعل',
            yt: 'https://www.youtube.com/watch?v=6QdiEQgfjc8&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=117',
            page: 79,
            deck: '0b3f69ad15f14d3695a98747753b73e3',
        },
        57: {
            title: '57. Hidayatun Nahw Lesson 57 اسم المفعول            ',
            slides: 'Hidayatun Nahw 57 القسم الأول، الخاتمة، الفصل الثامن، اسم المفعول',
            yt: 'https://www.youtube.com/watch?v=S6CP6JIeuZs&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=118',
            page: 80,
            deck: '87c3a232d60c4245880eab452983f2b4',
        },
        58: {
            title: '58. Hidayatun Nahw Lesson 58 الصفة المشبهة باسم الفاعل            ',
            slides: 'Hidayatun Nahw 58 القسم الأول، الخاتمة، الفصل التاسع، الصفة المشبهة باسم الفاعل',
            yt: 'https://www.youtube.com/watch?v=KNttYkc3wCM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=119',
            page: 80,
            deck: '1c294f51839e425bb34eaf0166625159',
        },
        59: {
            title: '59. Hidayatun Nahw Lesson 59 اسم التفضيل            ',
            slides: 'Hidayatun Nahw 59 القسم الأول، الخاتمة، الفصل التاسع، اسم التفضيل',
            yt: 'https://www.youtube.com/watch?v=oHv3tUASEnM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=120',
            page: 82,
            deck: '63102e2e035f42ff99fce12768a094cc',
        },



        60: {
            title: '60. Hidayatun Nahw Lesson 60 الفعل',
            slides: 'Hidayatun Nahw 60 القسم الثاني،',
            yt: 'https://www.youtube.com/watch?v=CRRi2_mNk0M&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=121',
            page: 84,
            deck: 'a70ee028fd2044a49f40814ac44f19e0',
        },

        61: {
            title: '61. Hidayatun Nahw Lesson 61 الفصل الأول، أصناف إعراب الفعل',
            slides: 'Hidayatun Nahw 61 القسم الثاني، الفصل الأول، أصناف إعراب الفعل',
            yt: 'https://www.youtube.com/watch?v=UKqU4IIgxTA&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=122',
            page: 86,
            deck: 'eb3ea55d78d54997a9d1c731c2d2e107',
        },

        62: {
            title: '62. Hidayatun Nahw Lesson 62 عامل المرفوع',
            slides: 'Hidayatun Nahw 62 القسم الثاني، الفصل الثاني، عامل المرفوع',
            yt: 'https://www.youtube.com/watch?v=LkPDfKULCgU&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=123',
            page: 87,
            deck: 'e37a9f3352304bcb953efa93cf7e8237',
        },

        63: {
            title: '63. Hidayatun Nahw Lesson 63 نواصب المضارع',
            slides: 'Hidayatun Nahw 63 القسم الثاني، الفصل الثالث، نواصب المضارع',
            yt: 'https://www.youtube.com/watch?v=vRkrvRlUu-E&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=124',
            page: 87,
            deck: '88e119c7eb804db6b7a4c67f7dd72107',
        },

        64: {
            title: '64. Hidayatun Nahw Lesson 64 جوازم المضارع            ',
            slides: 'Hidayatun Nahw 64 القسم الثاني، الفصل الرابع، جوازم المضارع',
            yt: ['https://www.youtube.com/watch?v=65AXHO-iZOQ&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=125',
                'https://www.youtube.com/watch?v=KLAwirXCwww&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=126',
                'https://www.youtube.com/watch?v=4HgrlRRHSus&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=127'],
            page: 89,
            deck: '8eae832bf770452696cb536df0054eac',
        },
        65: {
            title: '65. Hidayatun Nahw Lesson 65 الأمر            ',
            slides: 'Hidayatun Nahw 65 القسم الثاني، الأمر',
            yt: 'https://www.youtube.com/watch?v=kDaQ9OX9PSM&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=128',
            page: 93,
            deck: '18c023f6e9ed428a9b2b9aa04cd1fa8f',
        },
        66: {
            title: 'Hidayatun Nahw Lesson 66 الفعل المجهول            ',
            slides: 'Hidayatun Nahw 66 القسم الثاني، الفصل الخامس، الفعل المجهول',
            yt: 'https://www.youtube.com/watch?v=Hu0Uv0a1vbw&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=129',
            page: 94,
            deck: '9d494c06dc7a4c10b26292baf443288b',
        },
        67: {
            title: 'Hidayatun Nahw Lesson 67 الفعل المتعدي واللازم            ',
            slides: 'Hidayatun Nahw 67 القسم الثاني، الفصل السادس، المتعدي واللازم',
            yt: 'https://www.youtube.com/watch?v=A5Lbg9VFxHY&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=130',
            page: 95,
            deck: '87a2d1c800d841cc95f6ac9f37b12673',
        },
        68: {
            title: 'Hidayatun Nahw Lesson 68 أفعال القلوب             ',
            slides: 'Hidayatun Nahw 68 القسم الثاني، الفصل السابع، أفعال القلوب',
            yt: ['https://www.youtube.com/watch?v=YjrSaSYOt0Y&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=131',
                'https://www.youtube.com/watch?v=JF9e-k2Etr4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=132',
            ],
            page: 96,
            deck: '0b699e88232c4108a7c7353fc2c3dca1',
        },
        69: {
            title: 'Hidayatun Nahw Lesson 69 الأفعال الناقصة            ',
            slides: 'Hidayatun Nahw 69 القسم الثاني، الفصل الثامن، الأفعال الناقصة',
            yt: 'https://www.youtube.com/watch?v=bVNSrOfJ-5o&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=133',
            page: 98,
            deck: '6ca3d12ec5904f428475a23fdb6e1c64',
        },
        70: {
            title: 'Hidayatun Nahw Lesson 70 أفعال المقاربة            ',
            slides: 'Hidayatun Nahw 70 القسم الثاني، الفصل التاسع، أفعال المقاربة',
            yt: 'https://www.youtube.com/watch?v=Q539OmZhV80&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=134',
            page: 100,
            deck: 'a494a18fd79b46a6b7bb75af476879cf',
        },


        71: {
            title: 'Hidayatun Nahw Lesson 71 فعلا التعجب            ',
            slides: 'Hidayatun Nahw 71 القسم الثاني، الفصل العاشر، أفعال التعجب',
            yt: 'https://www.youtube.com/watch?v=ojHKS5SkAAo&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=135',
            page: 101,
            deck: '782e98e71b46421dbd03e0be2d41958d',
        },
        72: {
            title: 'Hidayatun Nahw Lesson 72 أفعال المدح والذم            ',
            slides: 'Hidayatun Nahw 72 القسم الثاني، الفصل الحادي عشر، أفعال المدح والذم',
            yt: 'https://www.youtube.com/watch?v=7ESB8RaFjPo&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=136',
            page: 102,
            deck: 'fc7b8f119eb24d8080176d724ad2529f',
        },
        73: {
            title: 'Hidayatun Nahw Lesson 73 حرف الجر            ',
            slides: 'Hidayatun Nahw 73 القسم الثالث، الفصل الأول، حرف الجر',
            yt: ['https://www.youtube.com/watch?v=Bf1JkDzqyA4&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=137',
                'https://www.youtube.com/watch?v=_kPAF5HTh6E&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=138',
                'https://www.youtube.com/watch?v=4v8ZxgAVrLY&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=139',
                'https://www.youtube.com/watch?v=X8jf9AcbnX0&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=140',
                'https://www.youtube.com/watch?v=v8Sf-6UJM9Y&list=PLzn0qdi6JpdtdAyaM2yvvY1Yk9i4EpLHD&index=141',
            ],
            page: 103,
            deck: '4c5bb637bcd2468cb001ce82123c5001',
        },
        74: {
            slides: 'Hidayatun Nahw 74 القسم الثالث، الفصل الأول، الحروف الشبهة بالفعل',
            page: 109,
            deck: '43a94accd67c40f7bfc7baf954472298',
        },





    },
};